# CRMEB 相关配置
crmeb:
  version: CRMEB-JAVA-MER-v1.7 # 当前代码版本
  domain: #配合swagger使用 # 待部署域名
  wechat-api-url:  #请求微信接口中专服务器
  asyncConfig: false #是否同步config表数据到redis
  asyncWeChatProgramTempList: false #是否同步小程序公共模板库
  #imagePath: /Users/mac/tools/code/finance/crmebimage/ # 服务器图片路径配置 斜杠结尾
  imagePath: /usr/local/app/crmebimage/ # 服务器图片路径配置 斜杠结尾
  retailStoreBrokerageRatio: 30 #佣金返佣比例和上限
  activityStyleCachedTime: 10 #活动边框缓存周期 秒为单位，生产环境适当5-10分钟即可
  selectProductLimit: 100 # 商品选择 指定商品上线
  productTagCacheMinutes: 10 # 商品标签缓存分钟数

server:
  port: 20800

spring:
  profiles:
    #  配置的环境
    active: dev
    #  数据库配置
  servlet:
    multipart:
      max-file-size: 50MB #设置单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.251.17:23306/cremb-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true # MySQL Connector/J 8.X 连接的示例
    username: root
    password: blackstone2008_p@ssw0rd
  redis:
    host: 120.55.185.164 # 地址
    port: 6379 # 端口
    password: gsafety!ABC2025 # 密码，建议生产环境开启
    timeout: 30000 # 连接超时时间（毫秒）
    database: 0  #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
third-party:
  adminBaseUrl: https://admin.xumuyouxuan.com
  accessToken:  eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyQ29udGV4dCI6IntcInVzZXJuYW1lXCI6XCJhZG1pblwiLFwibmlja05hbWVcIjpcIueuoeeQhuWRmFwiLFwiZmFjZVwiOlwiaHR0cDovLzEuOTIuOTkuMTA4OjkwMDAvbGlsaXNob3AvTUFOQUdFUi9kZWZhdWx0Lzk5YWMxYTE3NjM3OTRiYWQ5NDg2Yzc5ODc5ZDNlN2Q2LmpwZ1wiLFwiaWRcIjpcIjEzMzczMDYxMTAyNzc0NzYzNTJcIixcImxvbmdUZXJtXCI6ZmFsc2UsXCJyb2xlXCI6XCJNQU5BR0VSXCIsXCJpc1N1cGVyXCI6dHJ1ZX0iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc0Nzk5MjYyMX0.Iddn0DIzobs_Er8OBpz66AstAuVpZb8j7Cqcl84DMoI
  enabled: false  # 临时禁用第三方数据源
  xumuYouxuan:
    enabled: true
    databaseSyncMode: true  # 启用数据库同步模式
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xumuyouxuan.com:3306/myx-shop?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: yangzhi123456
    # Druid 连接池配置
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,slf4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

